name: Update Brew Repository
description: Updates the Homebrew tap repository with new release information

inputs:
  version:
    description: Version number to distribute
    required: true
  token:
    description: Token for accessing the Homebrew tap repository
    required: true
  tap_repo:
    description: Homebrew tap repository name
    required: false

runs:
  using: composite
  steps:
    - name: Get Release Info
      id: release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        # Get release info with URLs
        gh release view "v${{ inputs.version }}" --json assets > release.json

        # Get x86_64 binary info
        INTEL_URL=$(jq -r '.assets[] | select(.name | contains("x86_64-apple-darwin-homebrew")) | .url' release.json)
        echo "intel_url=$INTEL_URL" >> $GITHUB_OUTPUT

        # Get ARM binary info
        ARM_URL=$(jq -r '.assets[] | select(.name | contains("aarch64-apple-darwin-homebrew")) | .url' release.json)
        echo "arm_url=$ARM_URL" >> $GITHUB_OUTPUT

        # Get extension info
        jq -r '[.assets[] | select(.name | endswith(".wasm")) | {
          name: (.name | sub(".component.wasm$"; "")),
          url: .url
        }]' release.json > extensions.json

        # Download checksums
        gh release download "v${{ inputs.version }}" -p "checksums.txt"

    - name: Clone Tap Repository
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git clone "https://x-access-token:${{ inputs.token }}@github.com/${{ inputs.tap_repo }}.git" tap-repo

    - name: Generate Formula
      shell: bash
      run: |
        # Generate formula using our tool with direct inputs
        cargo run --package icp-distribution --bin generate_formula -- \
          --version "${{ inputs.version }}" \
          --checksums checksums.txt \
          --extensions extensions.json \
          --intel-url "${{ steps.release.outputs.intel_url }}" \
          --arm-url "${{ steps.release.outputs.arm_url }}" \
          --output tap-repo/Formula/icp-cli.rb

    - name: Commit and Push Changes
      shell: bash
      working-directory: tap-repo
      run: |
        git add Formula/icp-cli.rb
        git commit -m "Update icp-cli to version ${{ inputs.version }}"
        git push
