[workspace]
resolver = "2"

members = [
    "crates/icp-cli",
    "crates/icp-core",
    "crates/extensions/*",
    "crates/test-utils",
    "crates/icp-distribution",
]

default-members = [
    "crates/icp-cli",
    "crates/icp-core",
    "crates/icp-distribution",
]
