[workspace]
resolver = "2"

members = [
    "crates/dfx-cli",
    "crates/dfx-core",
    "crates/extensions/*",
    "crates/test-utils",
]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true
