[workspace]
resolver = "2"

members = [
    "crates/dfx-cli",
    "crates/dfx-core",
    "crates/extensions/identity",
    "crates/extensions/ledger",
    "crates/test-utils",
]

default-members = ["crates/dfx-cli"]
