[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
wasmtime = { version = "30.0", features = ["component-model", "async"] }
tokio = { version = "1.0", features = ["full"] }
dfx-cli = { path = "../dfx-cli" }

[dev-dependencies]
tokio-test = "0.4"
