[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
wasmtime = { version = "31.0.0", features = ["component-model", "async"] }
tokio = { version = "1.0", features = ["full"] }
icp-core = { path = "../icp-core" }

[dev-dependencies]
tokio-test = "0.4"
