name: Update APT Repository

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to update"
        required: true
        type: string

permissions:
  contents: read

jobs:
  update-apt:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Updating APT repository for version ${{ github.event.inputs.version }}"
