name: Update Homebrew Formula

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to update"
        required: true
        type: string

permissions:
  contents: read

jobs:
  update-formula:
    runs-on: macos-latest
    steps:
      - run: echo "Updating Homebrew formula for version ${{ github.event.inputs.version }}"
