name: Quick Install Script Deployment

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  quick-install:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Quick Install Script
        run: |
          echo "Deploying Quick Install Script version ${{ inputs.version }}"
