[package]
name = "icp-distribution"
version = "0.1.0"
edition = "2021"
description = "Distribution tools for the ICP CLI"
authors = ["ICP Team"]
license = "MIT"

[dependencies]
handlebars = "4.3.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.5.0"

[build-dependencies]
handlebars = "4.3.5"
