name: Update quick-install
description: Update quick-install

inputs:
  version:
    description: Version number to distribute
    required: true
  token:
    description: GitHub token for authentication
    required: true
  icp_binaries:
    description: List of standard ICP binary files to include
    required: true
  extension_binaries:
    description: List of extension files to include (for future use)
    required: true

runs:
  using: composite
  steps:
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - shell: bash
      run: |
        mkdir -p dist/binaries/icp

    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        gh release download "v${{ inputs.version }}" \
          --dir dist/binaries/icp \
          --pattern "checksums.txt"

    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        for binary in ${{ inputs.icp_binaries }}; do
          gh release download "v${{ inputs.version }}" \
            --dir dist/binaries/icp \
            --pattern "$binary"
        done


    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        for ext in ${{ inputs.extension_binaries }}; do
          gh release download "v${{ inputs.version }}" \
            --dir dist/binaries/icp \
            --pattern "$ext"
        done

    - shell: bash
      run: |
        cargo run --bin generate_scripts -- \
          --binary-path dist/binaries/icp \
          --output-dir dist \
          --domain "${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}" \
          --repo-url "https://github.com/${GITHUB_REPOSITORY}"

    - shell: bash
      run: |
        required_files=("install.sh" "install.ps1" "index.html" ".nojekyll")
        for file in "${required_files[@]}"; do
          if [ ! -f "dist/$file" ]; then
            echo "Error: Required file $file not found"
            exit 1
          fi
        done

    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages
        clean: true
