name: Update quick-install
description: Update quick-install

inputs:
  version:
    description: Version number to distribute
    required: true

runs:
  using: composite
  steps:
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - shell: bash
      run: |
        mkdir -p dist/binaries/icp

    - shell: bash
      run: |
        gh release download "v${{ inputs.version }}" \
          --dir dist/binaries/icp \
          --pattern "*"

    - shell: bash
      run: |
        cargo run --bin generate_scripts
        cp -r crates/icp-distribution/dist/* dist/

    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages
        clean: true
