name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string

permissions:
  contents: write

env:
  CLI_NAME: icp-cli

jobs:
  build-cli:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            variant: standard
            runs-on: ubuntu-latest

          - target: aarch64-apple-darwin
            variant: standard
            runs-on: macos-latest

          - target: x86_64-apple-darwin
            variant: standard
            runs-on: macos-latest

          - target: x86_64-pc-windows-msvc
            variant: standard
            runs-on: windows-2025

          - target: aarch64-apple-darwin
            variant: homebrew
            build_args: "--features homebrew --config prefix=/usr/local/homebrew"
            runs-on: macos-latest

          - target: x86_64-apple-darwin
            variant: homebrew
            build_args: "--features homebrew --config prefix=/usr/local/homebrew"
            runs-on: macos-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4

      - name: Build CLI
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --package icp-cli --target ${{ matrix.target }} --release

      - name: Rename to add variant
        shell: bash
        run: |
          BIN="target/${{ matrix.target }}/release/icp"
          NAME="${BIN%.*}"
          EXT=$(basename -- "${BIN}" | awk -F. 'NF>1 {print $NF}')

          if [ ! -z "${EXT}" ]; then
            EXT=".${EXT}"
          fi

          mv ${BIN} ${NAME}-${{ matrix.target }}-${{ matrix.variant }}${EXT}

      - uses: actions/upload-artifact@v4
        with:
          name: icp-cli-${{ matrix.target }}-${{ matrix.variant }}
          path: target/${{ matrix.target }}/release/icp*

  build-extensions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-tools
        run: cargo install wasm-tools

      - name: build multiply
        run: make CARGO_RELEASE=1 EXTENSION_NAME=multiply

      - name: build power
        run: make CARGO_RELEASE=1 EXTENSION_NAME=power

      - uses: actions/upload-artifact@v4
        with:
          name: extensions
          path: |
            target/wasm32-unknown-unknown/release/multiply.component.wasm
            target/wasm32-unknown-unknown/release/power.component.wasm

  create-release:
    needs: [build-cli, build-extensions]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4

      - name: Stage release assets
        run: |
          mkdir -p release-assets

          for d in icp-cli-*; do
            mv $d/icp-* release-assets/
          done

          mv extensions/* release-assets/

      - uses: softprops/action-gh-release@v1
        with:
          name: v${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          files: release-assets/*

  distribution:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering distribution for version ${{ inputs.version }}"

  distribution-quick-install:
    needs: distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/distribution/quick-install
        with:
          version: ${{ inputs.version }}

  distribution-apt:
    needs: distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/distribution/apt
        with:
          version: ${{ inputs.version }}

  distribution-homebrew:
    needs: distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/distribution/homebrew
        with:
          version: ${{ inputs.version }}
