name: Tests

on:
  push:
    paths:
      - "crates/**"
      - "Cargo.*"
      - ".github/workflows/**"
      - "Makefile"

  pull_request:
    branches: [main]
    paths:
      - "crates/**"
      - "Cargo.*"
      - ".github/workflows/**"
      - "Makefile"

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        platform:
          - runs-on: macos-latest
            target: aarch64-apple-darwin

          - runs-on: macos-latest
            target: x86_64-apple-darwin

          - runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - runs-on: windows-2025
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.platform.runs-on }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.platform.target }}

      - run: cargo test --workspace --target ${{ matrix.platform.target }}
